#!/bin/bash
set -e
cd "$(dirname "$0")"
source /usr/share/openfoam/etc/bashrc 2>/dev/null || true
blockMesh > log.blockMesh 2>&1
rm -rf 0 && cp -r 0.orig 0
setFields > log.setFields 2>&1
decomposePar -force > log.decomposePar 2>&1
mpirun --allow-run-as-root -np 4 interFoam -parallel -noFunctionObjects > log.interFoam 2>&1
